set -g history-limit 100000		      # Increase history limit
set -g base-index 1			            # Change index to start from 1
set-window-option -g pane-base-index 1 # Same for window index
unbind R
bind R source-file ~/.tmux.conf \; display "Reloaded ~/.tmux.conf"
unbind m
bind m set -g mouse on \; display "Mouse ON"
unbind M
bind M set -g mouse off \; display "Mouse OFF"

##################### TMUX PLUGIN MANAGER #####################
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'erikw/tmux-powerline'
#####################
set-environment -g 'SSH_AUTH_SOCK' ~/.ssh/ssh_auth_sock
set-option -g status on
set-option -g status-interval 2
#####################
if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins && tmux source-file ~/.tmux.conf'"
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
###############################################################
