set -g history-limit 100000		      # Increase history limit
set -g base-index 1			            # Change index to start from 1
set-window-option -g pane-base-index 1 # Same for window index
unbind R
bind R source-file $HOME/.tmux.conf \; display "Reloaded $HOME/.tmux.conf"
unbind m
bind m set -g mouse on \; display "Mouse ON"
unbind M
bind M set -g mouse off \; display "Mouse OFF"

##################### TMUX PLUGIN MANAGER #####################
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'erikw/tmux-powerline'
#####################
set-environment -g 'SSH_AUTH_SOCK' $HOME/.ssh/ssh_auth_sock
set-option -g status on
set-option -g status-interval 2
#####################
if-shell "[ ! -d $HOME/.tmux/plugins/tpm ]" \
  "run-shell 'bash -lc \"git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm\"'"
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '$HOME/.tmux/plugins/tpm/tpm'
###############################################################
