set -g history-limit 100000		      # Increase history limit
set -g base-index 1			            # Change index to start from 1
set-window-option -g pane-base-index 1 # Same for window index

##################### TMUX CUSTOM KEYBINDS #####################
unbind R
bind R source-file $HOME/.tmux.conf \; display "Reloaded $HOME/.tmux.conf"
unbind m
bind m set -g mouse on \; display "Mouse ON"
unbind M
bind M set -g mouse off \; display "Mouse OFF"

# Fast enable/disable pane broadcast
unbind X
bind X set-window-option synchronize-panes\; display-message "Broadcast Panes toggled"

# Switch panes using Alt-arrow without prefix
unbind Left
bind -n M-Left select-pane -L
unbind Right
bind -n M-Right select-pane -R
unbind Up
bind -n M-Up select-pane -U
unbind Down
bind -n M-Down select-pane -D

# puts the new pane to the left or above of the pane being split instead of to the right or below
bind Left split-window -b
# horizontal bind from " to Arrow-Right
unbind '"'
bind Right split-window -h
# makes a new pane spanning the whole width or height of the window instead of being constrained to the size of the pane being split.
bind Up split-window -f
# vertical bind from % to Arrow-Down
unbind %
bind Down split-window -v

##################### TMUX PLUGIN MANAGER #####################
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'erikw/tmux-powerline'
#####################
set-environment -g 'SSH_AUTH_SOCK' $HOME/.ssh/ssh_auth_sock
set-option -g status on
set-option -g status-interval 2
#####################
if-shell "[ ! -d $HOME/.tmux/plugins/tpm ]" \
  "run-shell 'bash -lc \"git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm\"'"
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '$HOME/.tmux/plugins/tpm/tpm'
###############################################################
